### ISSUE TITLE
///

### ISSUE THREAD

**Issue by shahabsiavash** [IranOpenFontGroup/Discussions#12]
///

**Comment by aziz** [comment]
شهاب جان ممنون به خاطر انتشار این قلم‌ها ولی قلم آزادی که مد نظر این گروه است باید سورس آن هم در دسترس قرار داشته باشد. 
اگر لطف کنی و سورس قلم‌ها را در گیت‌هاب منتشر کنی به لیست اضافه می‌کنیم.

**Comment by artlesshand** [comment]
؛سلام آقا شهاب
متوجه شدم که شما در وبسایتتون از قلم دیبا استفاده کردید که این قلم آزاد نیست،
به نظرم تغییرش بدید بهتر باشه

**Comment by shahabsiavash** [comment]
@aziz خواهش می‌کنم. متوجه نمی‌شم فونت‌های ایرانیان‌سنس و ایرانیان‌سریف به فونت‌لایبرری لینک داده شدن که.

**Comment by shahabsiavash** [comment]
@artlesshand 
دوست من تا جایی که بنده اطلاع دارم فونتها نباید فقط و فقط آزاد باشن تا بشه در وب و پروژه‌های شخصی استفاده کرد. حتا فونتهای لاتین هم پس از خرید در پروژه‌های کوچک و شخصی قابلیت استفاده دارن و اگر مخاطبان و بازدیدکنندگان افزایش پیدا کنن، حقوق تجاری بر اونها وارد میشه. تازه بگذریم که فونت دیبا اساسن لایسنسی تعریف نکرده. و دامون جان هم هیچ متن و بیانیه و دستورالعملی منتشر نکرده.

**Comment by artlesshand** [comment]
بله، ولی من جایی هم ندیدم رایگان منتشر شه، یا محک میفروشه با قلم‌برتر و من فکر می‌کنم استفاده‌ی رایگان از این قلم کار درستی نیست چون براحتی در دسترس همه هست الان.

**Comment by shahabsiavash** [comment]
@artlesshand 
نگرانی شما رو متوجه می‌شم ولی روال کار این طور نیست الان خانواده فونت فروتیگر که چند صد دلار قیمتش هست رو سایت‌های خارجی استفاده کردن و راحت میشه دانلودش کرد یعنی به قول شما الان در دسترس همه هست! آیا اونها جرمی مرتکب شدن؟ خیر! مسئولیت با دیگران هست که محصول رو ندزدن. اگر کسی حالا فونت رو برداره و کار غیر قانونی باهاش بکنه اون مقصره نه این سایتها و نه بنده. چرا که بر اساس استدلال شما هیچ فونتی نباید در وب استفاده بشه چون بالاخره ممکنه کسی بره از روی سورس نگاه کنه و برداره.

**Comment by behdad** [comment]
> حتا فونتهای لاتین هم پس از خرید در پروژه‌های کوچک و شخصی قابلیت استفاده دارن

اگر مجوزی وجود نداشته باشه که این اجازه رو بده، خیر، قابلیت استفاده ندارن.  تنها حالتی که استفاده قانونا و اخلاقا صحیح هست اینه که مجوزی باشه که اجازه‌ی استفاده رو بده.  حالا این مجوز می‌تونه یا آزاد و عمومی باشه، یا در ازای مبلغی به شما فروخته شده باشه.

اگه کسی نیومده به شما شکایت کنه معنی‌ش این نیست که استفاده صحیح است.

**Comment by shahabsiavash** [comment]
باز شروع شد. بدو بدو اومدن حقوق درس بدن! :))) فونت دیبا از طریق دو مرجع فقط فروخته میشه: محک و قلم برتر. هیچ کدام از این فروشنده‌ها و همچنین اطلاعات فایل فونت و همین طور طراح فونت هیچ گونه محدودیتی برای نحوه‌ی استفاده از فونت مشخص نکردن. حتا یک گام فراتر می رم و می‌گم در این حالت اگر کسی فونت رو برای دانلود هم بذاره کسی «قانونن» نمی‌تونه جلوش رو بگیره. اینا بحثهای حقوقی هست، حالا باز بگین که فلان کشور فلان طوره. ملت هم یک جور جو لایسنس اینا رو گرفته از صاحب اثر جلو زدن که بهشون بگی عزیز دلم میترا رو که لاینوتایپ زد شما ۱۷۰ یورو رو پرداخت کردی سی ساله داری استفاده می‌کنی؟ :))) سوراخ کردین هر دو وزن رو هم چاپ، هم وب، هم سرور...
باز هم دارم می‌گم این فونتی هست که حتا عوایدش صرف خیریه داره میشه وهیچ الزامی برای هیچ کونه استفاده‌ای براش تعیین نشده.
قوانین کپی‌رایت که ما اصلن خب نداریم جز مولفین و مصنفین، عشقی نیست که هر کی از هر کشوری واسه خودش مجری قانون بشه برای کشورهای دیگه. الان آمریکا با اروپا فرق می‌کنه. حتا آمریکا با دور زدن و گذاشتن عنوان نرم‌افزار تونستن واسه فونت کپی‌رایت تعیین کنن وگرنه خود تایپ‌فیس شامل کپی‌رایت نمیشه.
در حال حاضر در ایران تنها فونتی که مدون قوانین رو نوشته و شاید بر اساس قانون درب و داغون ایران بتونه پیگیری کنه فونت‌های ایران مسلم ابراهیمی هست که کاملن مشخص کرده حدود و محدودیت‌ها رو.
اون چیزی که شما میگی بر اساس قوانین اون طرف هست، تازه تو همین هم دعوا هست بین مرورگرها و فروشنده‌های فونت که مسئله رو حل کنن که اگر فونت وب استفاده شده چطوری جلوی دزدیده شدن فونتها رو بگیریم و اونجا هم شخص سارق مقصر هست نه کسی که سایت طراحی کرده.

**Comment by behdad** [comment]
همونجور که گفتی خودت این‌ها بحث‌های قانونی هست که تو دو خط کامنت نمی‌گنجه.  این که «تو ایران کپی‌رایت نداریم» که غلطه.  این که «صاحابش شاکی نشده» هم از نظر قانون و اخلاق دلیلِ محکمی نیست.

من هیچ کاری ندارم کی چیکار می‌کنه.  رو این گروه وظیفه‌ی خودم می‌دونم نظرم رو بدم.  شما برو هرجا هرکار می‌خوای بکن.  یا اگر اکثریت گروه ترجیح می‌دن نظر ندن، نمی‌دم.

یک توضیح هم بدم و برم: این که سی ساله کی چیو کپی کرده (چه من بوده باشم چه بقیه)، دلیل نمیشه که این کار درست باشه.  علتی که من، و بعضی‌های دیگه، اصرار داریم که حقوق درست و دقیق رعایت بشه، اینه که اگه ما خودمون شل بگیریم این موارد رو، چه‌جور می‌تونیم از بقیه انتظار داشته باشیم که خطا نکنند؟  برای مثال: همه می‌دونند که نیت این بوده که فونت ایران‌نستعلیق آزاد باشه.  ولی هیچ ریلیزِ آزادی ازش نشده.  حالا اگه من و شما به حکم این که «نیت این بوده»، برداریم و لایسنسش رو خودسر عوض کنیم و بازنشر کنیم، چطور می‌تونیم فردا به کسی که بدون اجازه با هر فونت دیگر این کار رو کرد خورده بگیریم؟

من دیگه حرفی ندارم در این مورد با شما دوستِ عزیز، ولی وظیفه‌ی خودم می‌دونستم تا اینجا رو بیان کنم.

**Comment by rastikerdar** [comment]
'''حتا یک گام فراتر می رم و می‌گم در این حالت اگر کسی فونت رو برای دانلود هم بذاره کسی «قانونن» نمی‌تونه جلوش رو بگیره'''

آقای سیاوش عزیز! این موضوع اینقدر بدیهی است که چنین می ماند من به شما بگویم این کتاب را بگذارید روی میز و شما بگذارید روی زمین. سپس به من بگویید تو که نگفتی نگذار روی زمین! فقط گفتی بگذار روی میز!
خب کسی که فونت را برای فروش گذاشته بدیهیست که معنایش اینست که این فونت نباید کپی بشه! چون اساسا اگر قرار بر آزادی کپی باشد که فروش معنایی ندارد!
یا مثلا شما اگر توی خیابان ببینید یک دوچرخه یک گوشه ای آزاد بدون قفل رها شده آیا بر می دارید و سوارش می شوید؟ سپس می گویید این نه صاحبی بالایش دیدم و نه سندی در کنارش. پس چون خودم پیدایش کردم اجازه استفاده دارم. طبیعتا شما اصل را بر آن می گذارید که آن دوچرخه صاحب دارد ولو اینکه در آن لحظه آنجا رها شده باشد. منظورم اینه که آدم ها یک سری پیش فرض های اخلاقی و حقوقی در زندگی دارند و اگر قرار بر برداشت های شخصی باشد که هرج و مرج بر جامعه حاکم می شود!

مبنای جامعه متمدن بر این اینست که هر اثری متعلق به صاحبش است و تنها در صورت اجازه او قابل بهره برداری می باشد.
برای جامعه آزاد یا اوپن سورس هم تنها در صورت ارائه سورس و همچنین سندی مبنی بر اجازه کپی، تغییر، استفاده و ... یک محصولی آزاد یا اوپن سورس محسوب میشود. به عبارتی فرض بر آن است که هر اثری صاحبی دارد و آزاد نمی باشد. مگر غیر آن ثابت شود.

در مورد فونت میترا اینطور که من متوجه شدم شورای عالی اطلاع رسانی یک سری فونت را برای استفاده رسما در اختیار عموم قرار داده و خب وقتی یک نهاد رسمی حکومتی چنین کاری کرده طبیعتا مبنای من آزادی در صرفا استفاده از (نه تغییر) آن فونت است.

حقیقتش آقای سیاوش عزیز، معیار این گروه، رعایت سفت و سخت این گونه مسائل است.
البته این برای من سوال است که اگر من قلم دیبا را خریدم از اونجایی که بیم کپی شدن آن می رود آیا اجازه استفاده در وب سایت دارم یا خیر؟ یعنی در اینکه آقای سیاوش اشتباه کرده باشند تردید دارم.

در مورد آثار هنری و ادبی:
[http://www.nobanlaw.com/f_faq-copyright](http://www.nobanlaw.com/f_faq-copyright)
البته نمی دونم اینجا فونت نرم افزار محسوب میشه و تایپ فیسش هنری یا غیر این است.

**Comment by shahabsiavash** [comment]
خب من به نظرم قهر کردن راه چاره نیست. چون ممکنه حتا با حرفهای مخالف به نتیجه برسیم و البته چیزهایی که شاید اطلاع نداریم رو هم بپذیریم.
@behdad 
شما حرف میزنی بعد میگی من کار ندارم. این درست نیست.
شما میگی اینکه کپی‌رایت نداریم غلطه، در حالی که قوانین رو اشتباه متوجه شدین. من اگر می‌خوندین نوشتم که یک قانون داریم به عنوان حمایت از حقوق مولفین و مصنفین و هنرمندان که در اصل قانون دهه ۴۰ مجلس شورای ملی هست که چند بند و ماده بهش اضافه کردن. قانون دیگر حق ثبت یا مالکیت معنوی هست که میشه چیزی شبیه به پتنت در خارج. البته در آمریکا شما نمیتونی برای فونت پتنت بگیری چون اختراع به حساب نمیاد.
حالا هر دوی این قوانین بیشتر روی کتاب و اثر هنری و تالیف و ترجمه تاکید دارن البته سعی کردن که نرم‌افزار و به سختی فونت رو هم درش جا بدن. 
و جفت این قانونها مثل دیگر قوانین ایران فقط روی کاغذ هستن. من نمیگم که خوشحالم از این قضیه اما دوستان باید متوجه شرایط و وضعیت ایران هم باشن. این که در رویا و تصورات خودمون غرق بشیم که یه شبه ایران بشه کشور غربی در زمینه حقوق مولف خنده داره.
بنابراین کپی‌رایت به اون معنا نداریم و آقای صابر شما در همون لینک میتونستین ببینین که نوشته ایران به هیچ معاهده بین المللی کپی رایت نپیوسته، بنابراین شما نمیتونی با قوانین خارجی در ایران اقامه دعوی کنی. صدا و سیمای مملکت هر چی فیلم و سریال و فوتبال کش میره و پخش میکنه. هیچ عواقبی هم نداره. لطفن دقت کنین من نمیگم این درسته، دارم میگم ما کپی رایت به معنای غربی نذاریم.
بحث اخلاقی که کلن متفاوته و من شاید بیش از ۵۰ تا مقاله از خارجیا خوندم که اونا هم سردرگمن که خلاصه فونتی که نصب هست رو میشه استفاده کرد؟ با فونت رایگان میشه لوگو زد؟ فونتی که یه برنامه نصب میکنه مال خودم میشه؟ اگه برنامه رو پاک کنم و فونتهاش که باقی نیمونه تکلیفش چیه؟ یعنی بعد از ده ها سال اونا هنوز مشکل دارن. اونوقت ما اینجا با این وضع قوانین نمی‌تونیم شخصن متخصص کپی رایت باشیم با تفسیر خودمون. قانون برای همینه. وقتی من میگم ما ضعف قانونی داریم برای همینه.
دومین مورد فروشگاه های فونت هستن که در خارج هر فونت معتبری رو شما از اونجا باید بخرین. ما نداریم در ایران. اولها فونتها تو برنامه ها بود، بعد سری برنا بود، بعد هم فارسی سازها و هیچ کدوم هم هیچ قانون و حق اسنفاده ای نداشتن. و اعتراضی هم نمی‌کردن. معلومه که شاکی شدن صاحب اثر مهمه. مثال معروفش فونت کوریر نیو آی‌بی‌ام هست که وقتی در سیستمهاش استفاده حقوقش کامل متعلق به خپدش بود. اما مردم شروع کردن کم کم به استفاده از اون و در طول سالها آی‌بی‌ام هیچ شکایتی نکرد و حتا وقتی ازش سوال میشد، می‌گفت مشکلی نذاره که نهایتن به طور ضمنی و شفاهی باعث آزاد یا رایگان شدن فونت شد. اگر قراره حرفه ای بشه داستان فونت،  فروشنده هم باید حرفه‌ای رفتار کنه. وقتی مریم سافت نمیدونه لایسنس چیه این مشکل اون هم هست. 
در مورد ایران نستعلیق هم بله غوض کردن یک فونت کلن درست نیست اما شما باید دقت کنی که (من خودم یادمه شورای عالی اطلاع رسانی این فونت رو ریلیز کرد من هم یک مقاله راجع بهش نوشتم همون موقع) در واقع از اطلاعیه ش معلوم بود منظورش یه جورایی پابلیک دومین هست ولی چون سوادش رو نداشتن و جا نیفتاده بود نوشتن برای دانلود. متن بیانیه واضح بود، ولی قانون ایران اصلن پابلیک دومین و فریور و اوپن سورس و اینا نداره، دلیلش اینه که کسی به کار نمیبره. دوست عزیز ما قانونگذار نیستیم، ما نمی توتیم برای خودمون قانون کشور دیگه رو اجرا کنیم.
چرا ایران به معاهده کپی رایت نمی پیونده؟ علاوه بر دلایل مذهبی که مالکیت خصوصی و رویالتی رو خوششون نمیاد بحث اینه که کل صنعت مدیا و کامپیوتر و طراحی گرافیک یک شبه نابود میشه بعد از پیوستن به کپی رایت! کی میتونه برای کل نرم افزارهایی که داره به دلار پول بپردازه؟ این که بگیم درستش همینه در حد شعار هست. واقعیت رو باید دید. فوتوشاپ، ایلوستریتور، ایندیزاین، آفیس، پرمییر، ویندوز و حتا برنامه های فونت کریتور و فونت لب که دوستان باهاش فونت پولی میسازن خودشون دزدین :)) و یه قانونی بود یه جا که فکر کنم میگفت شما اگر از راه غیر قانونی و دزدی محصولی تولید کنی مشمول هیچ حقی برات نمیشه. تکرار میکنم من هیچ کدوم اینا رو دوست ندارم، چون برای کار خودمون هم بده. ولی واقعیتها خیلی جدی تر از شعار دادن هست.
صایر جان مثال شما در مورد دوچرخه وارد نیست، چون ما اساسن چیزی به اسم «دوچرخه رایگان» نداریم، اما «فونت رایگان» داریم. کانسپتی که وجود داره باید فروشنده تعیین کنه که چجور باید ازش استفاده شه و چون فروشنده ایرانی بعضی از فونتها بر اساس قوانین حقوق مولفین و ثبت مالکیت محدودیتی وضع نکرده، دیگه نکرده. 
مثالش واضحه: شما اگه فونتی رو در نروژ طراحی کنی و مشمول معاهده کپی رایت بین اروپا و آمریکا نکنی، در آمریکا می تونن خود طراحی فونت رو قانونی بردارن و مثلن پرینتش کنن تک تک گلیفها رو و دوباره با اسم دیگه منتشر کنن. مثال من برای اینه که ما قوانین رو بشناسیم. 
در مورد فونت میترا شورای عالی اطلاع رسانی اصلن اساسن حق تغییر یا منتشر کردن فونت میترا یا خیلی دیگه از فونتها رو نداشته و هنوز هم نداره! خیلی جالبه که فونت دیبا که هیچ گونه حقوقی برای استفاده در وب درخواست نکرده و فرضن من بخوام برای پیج لود پایین سایت شخصی خودم حقش رو بپردازم، اصلن معلوم نیست به کی باید بپردازم و بر اساس کدام قانون!! محکوم شدم ولی میترا که سُر و مُر و گنده صاحبش مشخصه و کلیه حقوق استفاده ش رو منتشر کرده شما میگین که چون حکومت گفته حله؟؟ 
در ضمن بنده فونت دیبا رو تغییر ندادم و برای فروش عرضه نکردم. حتا اگر فونت دیبا درخواست حقوق برای استفاده در وب می‌کرد که نکرده باز هم بازدیدکنندگان سایت  من می تونستن فونت رو بردارن و از دست من کاری ساخته نبود.
@rastikerdar

**Comment by artlesshand** [comment]
<div dir='rtl' align='right'>
من نمی‌دونم شما چرا انقدر مقاومت دارید، چه انتظاری میشه از بقیه داشت وقتی خود شما که تایپ‌فیس کار کردی انقدر راحت توجیه می‌کنی؟
‌<br/>‌<br/>
من کاری به قانون و حکم و پتنت و غیره ندارم، به نظرم اخلاقیه که اگر کسی تولیدش رو برای فروش گذاشته، با اجازه‌ی خودش تولیدش رو استفاده کنم. حالا که وضع حقوق تولیدکننده‌ها در کشور بده، خودم سعی می‌کنم رعایت کنم و به فکر درآمد طراح قلم باشم که داره با زحمت زیاد یه محصول رو با کلی تهدید عرضه می‌کنه. همین پی‌سی‌دانلود منتظره فونت ببینه یجا، سریع میذاره تو سایتش برای دانلود. قلم صابر رو تو اولین نسخه‌ها گذاشت و الان خدا می‌دونه چند نفر اون نسخه‌ی پر مشکل رو استفاده می‌کنن.
‌<br/>‌<br/>
حرف من اینه: ما که می‌دونیم چه خبره اوضاع باید هوای هم رو داشته باشیم. اصلا آقای خانجانزاده پولاش از پارو بالا میره، یا فایل فونتش رو بدون لایسنس و چیزی گذاشته برای فروش. اخلاق حکم می‌کنه که حداقل من کسی نباشم که تهدید مالی و یا معنوی به اون شخص وارد کنه.
‌<br/>‌<br/>
غیر از این باشه، ما ۴۰۰ صفحه هم مدارک حقوقی بذاریم وسط، باز میشه یه گریز اون وسط زد.
‌<br/>‌<br/>
این نظر منه، حالا شما ممکنه با استدلال‌های دیگه ردش کنی.
‌<br/>
ممنونم ./
</div>

**Comment by shahabsiavash** [comment]
@artlesshand 
دوست عزیز. خب شما نمی‌دونم چرا متن رو نمی‌خونین و مدام همون حرف رو تکرار می‌کنین؟ 
فونت دیبا شرط استفاده برای وب تعیین نکرده. فونت فروخته شده با **هیچ قیدی** در استفاده. تنها قید اینه که من فونت رو مستقیم **تغییر** ندم و به **فروش** نرسونم یا  برای **دانلود** نذارم. این همه داستان من نوشتم، شما میگی پی‌سی‌دانلود؟؟ من گفتم بذارن رو پی‌سی‌دانلود مگه؟؟
من چه کار به پول دامون دارم؟ هر چی داره یا نداره نوش جونش. 

این که فونت وزیر رو به اشتباه گذاشتن، چه ربطی به اینجا داره؟ شما اصلن اطلاع دارین که در ناف آمریکا هم فونت تجاری رو میشه در وب استفاده کرد؟؟ خب اونجا هم پس کسی نباید بذاره رو سایتش با اینکه پول و لایسنسش رو خریده؟ چون ممکنه کسی سورس رو باز کنه و فونت رو ورداره؟؟

یا این استدلال شما، ادوبی در هر برنامه‌ش از صدها دلار فونت تجاری استفاده می‌کنه و همه رو نصب می‌کنه رو هارد. و حتا برنامه رو پاک کنی فونتها سر جاش هست. خب الان در این حالت باید طراح فونت حمله کنه به ادوبی که چرا این کار رو کرده؟

فکر می‌کنم شما شرایط مربوط به استفاده فونت از **فونت فیس** رو نمی‌دونین جسارتن و تصور می‌کنین هیچ فونتی نباید در سورس باشه. تکرار می‌کنم کسی که فونت رو بکشه بیرون از هر سایتی مجرم هست نه کسی که استفاده کرده.

**Comment by shahabsiavash** [comment]
@aziz 

من همچنان نمی‌دونم سورس رو منتشر کنیم یعنی چی؟ شاید تازه عضو شدنم در گیت‌هاب باعثش باشه.

**Comment by rastikerdar** [comment]
سیاوش جان من روز اول فایل های باینری رو گذاشتم روی گیتهاب که دوستان به من گفتن سورسش هم بزار. در واقع منظورشون همون فایل مرجع هنگام کار با برنامه ای که با اون فونت رو طراحی می کنید هست. مثلا فونت آزاد پی‌فونت رو ببین سورسش همون فایل های گلیف ها هست که توسط برنامه تولید شده. من هم چون با فونت فورج کار می کردم فایل خود فونت فورج رو به عنوان سورس اضافه کردم به مخزن. شما هم فکر می کنم باید شبیه پی‌فونت عمل کنید و البته یک لایسنس آزاد هم برای فونت هاتون نیازه که اضافه کنید.
OFL خیلی رایجه

فقط یه موضوع مهم اینه که فونتی که ساختید اگر از صفر بوده که مشکلی نیست اما اگر از روی فونت دیگری ساختید باید حتما تکلیف لایسنس اون فونت مبنا روشن باشه. اگر امتیازش رو داشتید که مشکلی نیست اگر نه که باید مجوز تغییر فونت به شما داده شده باشه. مثلا خودش فونت آزاد باشه.

ضمنا گیتهاب جای خیلی خوبیه برای انتشار سورس.

**Comment by shahabsiavash** [comment]
@rastikerdar 

ممنون صابر جان.من این فونتها رو حدود ۷-۸ سال پیش با فونت کریتور ۵ یا ۵.۵ طراحی کردم. فکر می‌کنم پس منظور فایل های اف‌سی‌پی فونت‌کریتور باشه ؟؟؟

من فایل دیگه‌ای ندارم. و فونتها رو هم داخل برنامه طراحی کردم و از ایلوستریتور و اینا استفاده نکردم 

در ضمن ۲ فونت به قولی از صفر هست اما دو تای دیگه همون طور که از اسمشون پیداست از روی میترا بولد ساخته شده، ۸ سال پیش این داستان‌های لایسنس و اینا نبود خب.
و فکر می‌کنم با توجه به استفاده و تولید و انتشار و پخش و تغییر صد هزار باره‌ی میترا توسط هر شرکت و گروه و طراح فونتی و پیرو بحث‌های چند روز گذشته میترا باید آزاد تلقی شه درسته؟

اگر هم نمیشه مهم نیست. دو فونت دیگر رو می‌ذارم.

**Comment by shahabsiavash** [comment]
با تشکر از صابر عزیز هر دو خانواده در گیت‌هاب منتشر شدند به همراه سورس و لایسنس و توضیح

دیگه تصمیمش با شما :)

[SI47ASH_Sole Fonts](https://github.com/shahabsiavash/SI47ASH_Sole-Fonts)

[SI47ASH_MitraDeformed Fonts](https://github.com/shahabsiavash/SI47ASH_MitraDeformed-Fonts)


@aziz @rastikerdar

**Comment by shahabsiavash** [comment]
**ختم کلام درباره فونت دیبا**

با وجود اینکه از لحاظ قانونی و اخلاقی هیچ لزومی به پرسش از فروشنده فونت نبود. چرا که **تنها شرط هنگام خرید کپی نکردن فایل فونت** بود.

![screenshots_2016-07-01-23-02-05](https://cloud.githubusercontent.com/assets/20119395/16546249/9f39a7ca-4159-11e6-9b2b-a4e14751c01f.png)

اما با این وجود در ایمیلی کامل واضح درباره شرایط استفاده فونت دیبا از فروشنده رسمی سوال شد و این هم جواب:

![screenshots_2016-07-03-14-48-08](https://cloud.githubusercontent.com/assets/20119395/16546255/c71d16dc-4159-11e6-9219-057180f3f189.png)

امیدوارم دیگه این بحث خاتمه پیدا کنه و دوستان از خود فروشنده هم در زمینه حق و حقوق فراتر نرن! 
:)

@artlesshand @behdad @rastikerdar

**Comment by artlesshand** [comment]
<div dir='rtl' align='right'>
جناب شهاب،<br />
اول اینکه بنده فکر می‌کنم پاسخ محک چیزی رو بر خلاف صحبت من و دیگران به اثبات نمی‌رسونه، ضمنا اگر پاسخ دقیق‌تری مد نظرتون هست،  از خود آقای خانجانزاده و یا مریم‌سافت در مورد استفاده‌ به شکل وب‌وفونت بپرسید.<br />
دوم اینکه من علاقه‌ای به ادامه‌ی این بحث با شما ندارم چون ادبیات بحث کردنتون رو نمی‌پسندم. <br />
موفق باشید ./
</div>

**Comment by shahabsiavash** [comment]
متاسفم که وقتم رو هدر دادم برای توضیح دادن اصول و قواعدی که کوچکترین اطلاعی ازش ندارین و پافشاری می‌کنین بر چیزی که هیچ مبنایی نداره.

متاسفم که بحث مربوط به فونتهای آزاد من رو منحرف کردین و وقت همه رو گرفتین.

برین مطالعه کنین که بدونین نحوه کار خریدار، طراح و فروشگاه چطوره در همه جای دنیا. اوج بی‌اطلاعی‌تون اونجاس که میگین از مریم‌سافت! و دامون سوال بشه که هیچ موضوعیتی نداره وقتی فونت از محک تهیه شده!! یه مقدار مطالعه بد نیست. اینجوری که فونت فروتیگر تو هزار تا سایت عرضه شده، مردم باید از تک تک اونا شرایط استفاده بپرسن و بعد هم از طراح و وارثش لابد!!
