### ISSUE TITLE
------

### ISSUE THREAD

**Issue by shahabsiavash** [IranOpenFontGroup/Discussions#15]
یه ماه شده فک کنم یه نفر یه جواب نداده. واقعن عجیب و غریبه که تو مبحث فونت آزاد هم این رفتارهای قهر و لجبازی کودکانه وجود داره. دو تا بحث کردیم همه غیب شدن از گروه. بحث بی‌ربط و بیهوده و بی‌پایه و اساس که اصلن من شروع نکردم. و تصور هم بر اینه که چون ما یه چیزی رو به غلط بهش باور داریم کسی نباید مخالفت کنه! واقعن که.

**Comment by rastikerdar** [comment]
صبوری کنید آقای سیاوش. آهسته و پیوسته.
:)

**Comment by zoghal** [comment]
با صابر موافقم
در مقابل خیلی از مسايل نمیشه سریع جبهه گرفت باید بهش زمان داد تا کسانی که مدعی هستند و شو آف می‌کنند بواسطه خودشون نقاب از چهره پلیدشان برداشت و رو سیاهشون کرد.

## گر صبر کنی ز قوره حلوا سازم، اونم چه حلوایی :)

بازگشت زغال

**Comment by rastikerdar** [comment]
البته من با شما صالح جان موافق نیستم. منظور من چیز دیگری بود.
