### ISSUE TITLE
نصب‌نشدن فونت ابوذر در لینوکس

### ISSUE THREAD

**Issue by afshin-ir** [IranOpenFontGroup/Discussions#25]
من فونت abo-thar را در لینوکس نصب کردم. نسخهٔ 1.03 را هم نصب کردم که ظاهراً جدیدترین نسخه‌اش است. 
از این فونت برای درج عبارت‌های دعایی، مانند علیه‌السلام، استفاده می‌شود. 
عجیب است که پس از نصب‌شدن و حتی به‌روزرسانی Cache فونت‌ها، باز هم در فهرست فونت‌های نصب‌شدهٔ هیچ‌یک از برنامه‌ها اضافه نمی‌شود! 

فونت را ضمیمهٔ همین گزارش کرده‌ام.

**Comment by afshin-ir** [comment]
در واقع فونت نصب می‌شود؛ اما نام فونت در فهرست فونت‌ها نمایش داده نمی‌شود و فقط پیش‌نمایش فونت را در فهرست فونت‌ها می‌بینید!

![image](https://user-images.githubusercontent.com/14938202/50372395-0d474380-05e3-11e9-8370-c811e7633ec9.png)

**Comment by zoghal** [comment]
پارامتر‌های نام‌گذاری به درستی انجام نشده است!

**Comment by afshin-ir** [comment]
امکانش هست برای اصلاح آن پارامترها قبول زحمت کنید؟
دربارهٔ اشتباه‌های نام‌گذاری هم اگر توضیحی بدهید، ممنون خواهم بود.

**Comment by zoghal** [comment]
اگر امکان داشته باشد پاسختان را در تلگرام می‌دهم. لطفا با من تماس بگیرید t.me/zoghal
