### ISSUE TITLE
قلم‌های کپی

### ISSUE THREAD

**Issue by behdad** [IranOpenFontGroup/Discussions#9]
به نظر من درست نیست قلم‌هایی رو که بدونِ اجازه‌ی طراح‌شون کپی و به اصطلاع بعضی «ریدیزاین» شده‌اند در این گروه به معرفی بگذاریم.  این کار خلافِ اخلاقِ آزاد است و من به نوبه‌ی خود از پروژه‌ای که چنین قلم‌هایی را معرفی کن حمایت می‌نکنم.

**Comment by aziz** [comment]
علاوه بر این لحن و توضیحات هم مناسب نبود. اینجا جای افشاگری و انقلاب که نیست.

**Comment by rastikerdar** [comment]
ای کاش پای این گروه به این جور مسائل باز نشه.

**Comment by behdad** [comment]
علتی که عنوان کردم این هست که روی صفحه‌ی ویکی لینک هست به چنان پروژه‌هایی.  وگرنه من هم امیدوارم پای این بحث‌ها تو این گروه باز نشه.

**Comment by aziz** [comment]
حذف کردم. امیدوارم صالح هم درک کنه که اینجا برای قلم آزاد دور هم جمع شدیم. نفس طراحی مجدد یک کار بد نیست ولی اینجا میخواهیم از کارهای جدید و کدباز حمایت کنیم و به دنبال دعواهای حقوقی و یا حمله به دیگران نیستیم.

**Comment by zoghal** [comment]
خوشحال شدم بالاخره واکنشی از شما در این زمینه دیدم. :smile:  دیگه داشتم شک میکردم زیاد اهمیتی براتون نداره.

> این کار خلافِ اخلاقِ آزاد است و من به نوبه‌ی خود از پروژه‌ای که چنین قلم‌هایی را معرفی کن حمایت می‌نکنم

@behdad من هم موافقم، ولی ای کاش حداقل از پروژه‌هایی که بر اساس اخلاق آزاد بنا شدند یک حمایت کوچیک از شما شاهد بودیم تا دلخوش میشدیم. والا به یک ستاره زدند هم قانع هستیم. اما…

@aziz خوب کاری کردید. من بابت این موضوع از همگی عذرخواهی میکنم.

به امید اینکه حرف‌ها با عمل‌ها  یکی شود. یکطرفه و جهت دار به موضوعات نگاه نکنیم.و مسايل و مشکلات رو با بحث منطقی حل و فصل کنیم. امین
